### ISSUE TITLE
build for android failed

### ISSUE THREAD

**Issue by leleliu008** [warmcat/libwebsockets#2328]
**reported error:**
```
lib/core/libwebsockets.c:213:29: error: implicit conversion loses integer precision: 'uint32_t' (aka 'unsigned int') to 'mode_t' (aka 'unsigned short') [-Werror,-Wimplicit-int-conversion]
                n = open(__file, __oflag, va_arg(ap, uint32_t));
                    ~~~~                  ^~~~~~~~~~~~~~~~~~~~
/usr/local/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/stdarg.h:19:29: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

android-ndk version: 21.3.6528147

**Comment by lws-team** [comment]
Does this help?

https://libwebsockets.org/git/libwebsockets/commit?id=25f417c95e3ec528eddd875864012d659863612b

it's also on main branch

**Comment by leleliu008** [comment]
it doesn't work for me. the reported log changed as following:

```
lib/core/libwebsockets.c:222:29: error: implicit conversion loses integer precision: 'unsigned int' to 'mode_t' (aka 'unsigned short') [-Werror,-Wimplicit-int-conversion]
                n = open(__file, __oflag, va_arg(ap, unsigned int));
                    ~~~~                  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/stdarg.h:19:29: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by lws-team** [comment]
OK... then this should solve it

https://libwebsockets.org/git/libwebsockets/commit?id=a2091bdbc8bb8593a21675c27ab612cf4e327d95

**Comment by leleliu008** [comment]
yes, it works now. but new error occured:

```
lib/misc/getifaddrs.c:93:20: error: implicit conversion changes signedness: 'size_t' (aka 'unsigned int') to 'int' [-Werror,-Wsign-conversion]
                ifconf.ifc_len = buf_size;
                               ~ ^~~~~~~~
lib/misc/getifaddrs.c:144:29: error: implicit conversion changes signedness: 'short' to 'unsigned int' [-Werror,-Wsign-conversion]
                (*end)->ifa_flags = ifreq.ifr_flags;
                                  ~ ~~~~~~^~~~~~~~~
/usr/local/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/linux/if.h:169:28: note: expanded from macro 'ifr_flags'
#define ifr_flags ifr_ifru.ifru_flags
                           ^
2 errors generated.
```

**Comment by lws-team** [comment]
This should help

https://libwebsockets.org/git/libwebsockets/commit?id=1929e1f128b859669b3424388e5a436b438d4ad8

**Comment by leleliu008** [comment]
yes, it works, and new error occured:

```
lib/core-net/network.c:70:14: error: implicit conversion changes signedness: 'socklen_t' (aka 'int') to 'size_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
                            name, (socklen_t)name_len, NULL, 0, 0);
                                  ^~~~~~~~~~~~~~~~~~~
/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.g4gyUstR/lib/core-net/network.c:84:11: error: implicit conversion changes signedness: 'socklen_t' (aka 'int') to 'size_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
                                name, (socklen_t)name_len, NULL, 0, 0))
                                      ^~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by lws-team** [comment]
That's actually Android making its own nonstandard args for `getnameinfo()`... this should clean it up

https://libwebsockets.org/git/libwebsockets/commit?id=2012270bebe9b5c52d25f0ad7deb58f6fbb7066f

**Comment by leleliu008** [comment]
yes, you are right.

**POSIX:**
```
int
getnameinfo(
const struct sockaddr *restrict sa,
socklen_t salen,
char *restrict node,
socklen_t nodelen,
char *restrict service,
socklen_t servicelen,
int flags
);
```
**Android:**
```
int
getnameinfo(
const struct sockaddr* __sa,
socklen_t __sa_length,
char* __host,
size_t __host_length,
char* __service,
size_    t __service_length,
int __flags
);
```

**Comment by leleliu008** [comment]
@lws-team Thanks for you help. It can be correctly compiled.

**Comment by leleliu008** [comment]
following GitHub Actions workflow can test if compiled with Android-NDK:

```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-android-ndk:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - uses: actions/checkout@v2

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ndk-pkg $(brew --prefix)/bin

    - run: ndk-pkg update

    - run: ndk-pkg install libwebsockets
```
