### ISSUE TITLE
h1 client not chunking data correctly 

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2641]
Using lws-4.3-stable

I have a lws client reading from the k8s api but it is unable to see the '\n' and it sending data passed that character instead of chunking the message
This will cause lejp parse failed -2 

See below hex `0A` near `ADDED`

```
 U: test.c:1128 LWS_CALLBACK_RECEIVE_CLIENT_HTTP status = 200
 D: openssl-ssl.c:222 [wsicli|0|GET/h1/default/192.168.1.230]: SSL_read says 1024
 N: client-http.c:1393 lws_http_client_read: len 1024 SPIN chunk remaining 0
 N: client-http.c:1417 starting chunk size 2048 (block rem 1020)
 U: test.c:1152 LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ: read 1019
 U:
 U: 0000: 7B 22 74 79 70 65 22 3A 22 41 44 44 45 44 22 2C    {"type":"ADDED",
 U: 0010: 22 6F 62 6A 65 63 74 22 3A 7B 22 6B 69 6E 64 22    "object":{"kind"
 U: 0020: 3A 22 53 65 72 76 69 63 65 22 2C 22 61 70 69 56    :"Service","apiV
 U: 0030: 65 72 73 69 6F 6E 22 3A 22 76 31 22 2C 22 6D 65    ersion":"v1","me
 U: 0040: 74 61 64 61 74 61 22 3A 7B 22 6E 61 6D 65 22 3A    tadata":{"name":
 U: 0050: 22 6B 75 62 65 72 6E 65 74 65 73 22 2C 22 6E 61    "test","na
 U: 0060: 6D 65 73 70 61 63 65 22 3A 22 64 65 66 61 75 6C    mespace":"defaul
 U: 0070: 74 22 2C 22 73 65 6C 66 4C 69 6E 6B 22 3A 22 2F    t","selfLink":"/
 U: 0080: 61 70 69 2F 76 31 2F 6E 61 6D 65 73 70 61 63 65    api/v1/namespace
 U: 0090: 73 2F 64 65 66 61 75 6C 74 2F 73 65 72 76 69 63    s/default/servic
 U: 00A0: 65 73 2F 6B 75 62 65 72 6E 65 74 65 73 22 2C 22    es/test","
 U: 00B0: 75 69 64 22 3A 22 32 36 30 38 38 34 35 35 2D 31    uid":"26088455-1
 U: 00C0: 61 63 62 2D 34 65 62 63 2D 61 34 66 37 2D 63 39    acb-4ebc-a4f7-c9
 U: 00D0: 64 35 66 66 37 66 37 61 66 39 22 2C 22 72 65 73    d5ff7f7af9","res
 U: 00E0: 6F 75 72 63 65 56 65 72 73 69 6F 6E 22 3A 22 31    ourceVersion":"1
 U: 00F0: 35 33 22 2C 22 63 72 65 61 74 69 6F 6E 54 69 6D    53","creationTim
 U: 0100: 65 73 74 61 6D 70 22 3A 22 32 30 32 32 2D 30 35    estamp":"2022-05
 U: 0110: 2D 31 37 54 30 36 3A 30 37 3A 32 38 5A 22 2C 22    -17T06:07:28Z","
 U: 0120: 6C 61 62 65 6C 73 22 3A 7B 22 63 6F 6D 70 6F 6E    labels":{"compon
 U: 0130: 65 6E 74 22 3A 22 61 70 69 73 65 72 76 65 72 22    ent":"apiserver"
 U: 0140: 2C 22 70 72 6F 76 69 64 65 72 22 3A 22 6B 75 62    ,"provider":"kub
 U: 0150: 65 72 6E 65 74 65 73 22 7D 2C 22 6D 61 6E 61 67    ernetes"},"manag
 U: 0160: 65 64 46 69 65 6C 64 73 22 3A 5B 7B 22 6D 61 6E    edFields":[{"man
 U: 0170: 61 67 65 72 22 3A 22 6B 75 62 65 2D 61 70 69 73    ager":"kube-apis
 U: 0180: 65 72 76 65 72 22 2C 22 6F 70 65 72 61 74 69 6F    erver","operatio
 U: 0190: 6E 22 3A 22 55 70 64 61 74 65 22 2C 22 61 70 69    n":"Update","api
 U: 01A0: 56 65 72 73 69 6F 6E 22 3A 22 76 31 22 2C 22 74    Version":"v1","t
 U: 01B0: 69 6D 65 22 3A 22 32 30 32 32 2D 30 35 2D 31 37    ime":"2022-05-17
 U: 01C0: 54 30 36 3A 30 37 3A 32 38 5A 22 2C 22 66 69 65    T06:07:28Z","fie
 U: 01D0: 6C 64 73 54 79 70 65 22 3A 22 46 69 65 6C 64 73    ldsType":"Fields
 U: 01E0: 56 31 22 2C 22 66 69 65 6C 64 73 56 31 22 3A 7B    V1","fieldsV1":{
 U: 01F0: 22 66 3A 6D 65 74 61 64 61 74 61 22 3A 7B 22 66    "f:metadata":{"f
 U: 0200: 3A 6C 61 62 65 6C 73 22 3A 7B 22 2E 22 3A 7B 7D    :labels":{".":{}
 U: 0210: 2C 22 66 3A 63 6F 6D 70 6F 6E 65 6E 74 22 3A 7B    ,"f:component":{
 U: 0220: 7D 2C 22 66 3A 70 72 6F 76 69 64 65 72 22 3A 7B    },"f:provider":{
 U: 0230: 7D 7D 7D 2C 22 66 3A 73 70 65 63 22 3A 7B 22 66    }}},"f:spec":{"f
 U: 0240: 3A 63 6C 75 73 74 65 72 49 50 22 3A 7B 7D 2C 22    :clusterIP":{},"
 U: 0250: 66 3A 70 6F 72 74 73 22 3A 7B 22 2E 22 3A 7B 7D    f:ports":{".":{}
 U: 0260: 2C 22 6B 3A 7B 5C 22 70 6F 72 74 5C 22 3A 34 34    ,"k:{\"port\":44
 U: 0270: 33 2C 5C 22 70 72 6F 74 6F 63 6F 6C 5C 22 3A 5C    3,\"protocol\":\
 U: 0280: 22 54 43 50 5C 22 7D 22 3A 7B 22 2E 22 3A 7B 7D    "TCP\"}":{".":{}
 U: 0290: 2C 22 66 3A 6E 61 6D 65 22 3A 7B 7D 2C 22 66 3A    ,"f:name":{},"f:
 U: 02A0: 70 6F 72 74 22 3A 7B 7D 2C 22 66 3A 70 72 6F 74    port":{},"f:prot
 U: 02B0: 6F 63 6F 6C 22 3A 7B 7D 2C 22 66 3A 74 61 72 67    ocol":{},"f:targ
 U: 02C0: 65 74 50 6F 72 74 22 3A 7B 7D 7D 7D 2C 22 66 3A    etPort":{}}},"f:
 U: 02D0: 73 65 73 73 69 6F 6E 41 66 66 69 6E 69 74 79 22    sessionAffinity"
 U: 02E0: 3A 7B 7D 2C 22 66 3A 74 79 70 65 22 3A 7B 7D 7D    :{},"f:type":{}}
 U: 02F0: 7D 7D 5D 7D 2C 22 73 70 65 63 22 3A 7B 22 70 6F    }}]},"spec":{"po
 U: 0300: 72 74 73 22 3A 5B 7B 22 6E 61 6D 65 22 3A 22 68    rts":[{"name":"h
 U: 0310: 74 74 70 73 22 2C 22 70 72 6F 74 6F 63 6F 6C 22    ttps","protocol"
 U: 0320: 3A 22 54 43 50 22 2C 22 70 6F 72 74 22 3A 34 34    :"TCP","port":44
 U: 0330: 33 2C 22 74 61 72 67 65 74 50 6F 72 74 22 3A 36    3,"targetPort":6
 U: 0340: 34 34 33 7D 5D 2C 22 63 6C 75 73 74 65 72 49 50    443}],"clusterIP
 U: 0350: 22 3A 22 31 37 32 2E 31 36 2E 30 2E 31 22 2C 22    ":"172.16.0.1","
 U: 0360: 74 79 70 65 22 3A 22 43 6C 75 73 74 65 72 49 50    type":"ClusterIP
 U: 0370: 22 2C 22 73 65 73 73 69 6F 6E 41 66 66 69 6E 69    ","sessionAffini
 U: 0380: 74 79 22 3A 22 4E 6F 6E 65 22 7D 2C 22 73 74 61    ty":"None"},"sta
 U: 0390: 74 75 73 22 3A 7B 22 6C 6F 61 64 42 61 6C 61 6E    tus":{"loadBalan
 U: 03A0: 63 65 72 22 3A 7B 7D 7D 7D 7D 0A 7B 22 74 79 70    cer":{}}}}.{"typ
 U: 03B0: 65 22 3A 22 41 44 44 45 44 22 2C 22 6F 62 6A 65    e":"ADDED","obje
 U: 03C0: 63 74 22 3A 7B 22 6B 69 6E 64 22 3A 22 53 65 72    ct":{"kind":"Ser
 U: 03D0: 76 69 63 65 22 2C 22 61 70 69 56 65 72 73 69 6F    vice","apiVersio
 U: 03E0: 6E 22 3A 22 76 31 22 2C 22 6D 65 74 61 64 61 74    n":"v1","metadat
 U: 03F0: 61 22 3A 7B 22 6E 61 6D 65 22 3A                   a":{"name":
 U:
 U: test.c:440 440 (LEJPCB_CONSTRUCTED)
 U: test.c:437 437 (LEJPCB_COMPLETE)
```
